<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/clase_3_arrays_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#Ejemplo array
ejemplo_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Este es un array: " , ejemplo_array)

Este es un array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
# acceder a una posición por su indice
print(ejemplo_array[2]) # los indices comienzan desde la posición 0
print(ejemplo_array[7])


# Ejemplo con varios indices y el último indice
print(ejemplo_array[[7,10,-1]])  # el último elemento se trae con el -1

3
8
[ 8 11 20]


In [10]:
# accedor a un rango del array
print(ejemplo_array[1:4]) # los dos puntos significa rango

[2 3 4]


In [11]:
# acceder a los primeros 3 números
print(ejemplo_array[:3])

[1 2 3]


In [12]:
# acceder a los últimos 3 numeros
print(ejemplo_array[-3:])

[18 19 20]


In [13]:
#EJERCICIOS PRACTICOS CON ARRAYS
temperaturas = np.array([15,18,22,25,24,20,17])

In [14]:
#Reto 1 (Indexación simple): Extraer el primer elemento 15 y el último elemento 17
print(temperaturas[0:-1])

[15 18 22 25 24 20]
