<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/clase_4_matrices_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# Creación de matriz de arrays
matriz = np.array([[1,2,3],
                  [4,5,6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [6]:
# atributos de los arrays
print("Numero de dimensiones: ", matriz.ndim)
print("Forma del array: ", matriz.shape)
print("Tamaño del array: ", matriz.size)
print("Tipo de dato del array", matriz.dtype)
#

Numero de dimensiones:  2
Forma del array:  (2, 3)
Tamaño del array:  6
Tipo de dato del array int64


In [7]:
# mostras elementos especificos de una matriz
print(matriz[0,1]) # Fila , # Columna
print(matriz[1,1]) # Fila , # Columna
#

2
5


In [8]:
# mostrar toda una fila
print(matriz[1])

[4 5 6]


In [9]:
# mostrr una columa completa
print(matriz[:,1])

[2 5]


In [11]:
# mostrar la primera fila y las 2 primeras columnas
print(matriz[1,:2])   #  :2 significa las 2 primeras columnas   1 significa la segunda fila

[4 5]


In [12]:
# suma de los elementos al interior de una matriz
print(matriz.sum()) # suma todos los elementos.
print(matriz.sum(axis=0)) # suma todos los elementos por columnas
print(matriz.sum(axis=1)) # suma las filas

21
[5 7 9]
[ 6 15]


## ACTIVIDADES BASICAS CON ARRAYS

In [16]:
# Análisis de temperaturas con arrays
temperaturas = np.array([29,31,28,30,27,32,33])
print(temperaturas)

[29 31 28 30 27 32 33]


In [17]:
# muestra la temperatura del tercer día.
print(temperaturas[2])

28


In [19]:
# Calcula la temperatura promedio de la semana
print(temperaturas.mean())

30.0


In [21]:
# Muestra las temperaturas mayores a 30 grados
mascara = temperaturas > 30
print(temperaturas[mascara])
# [31 32 33]

[31 32 33]


In [22]:
# Suma 1 grado a todas las emperaturas  y muestra el nuevo array
temperaturas = temperaturas + 1
print(temperaturas)

[30 32 29 31 28 33 34]


## Análisis de  ventas por región Matriz

In [25]:
ventas = np.array([
    [120,135,150,160], # Region del norte
    [100,110,115,130], # Región del sur
    [90,105,100,120] # Región Centro
])

print(ventas)

[[120 135 150 160]
 [100 110 115 130]
 [ 90 105 100 120]]


In [29]:
# 1. muestra las ventas del segundo trimestre para todas las regiones
print(ventas[:,1])

[135 110 105]


In [33]:
# Calcula las ventas totales por la región
print(ventas.sum(axis=1))

[565 455 415]


In [31]:
# Calcula las ventas totales por trimestre.
print(ventas.sum(axis=0)) # suma las ventas totales por columnas (trimestres)

[310 350 365 410]


In [32]:
totales_trimestre = ventas.sum(axis=0)
print(totales_trimestre.argmax()) #Existe una función de NumPy hermana de .max() que, en vez de devolver el valor máximo, te devuelve la posición (índice) donde se encuentra ese máximo. Se llama argmax (la "g" de "argument", literalmente "el índice/argumento que da el máximo").

3
