<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/clase_3_arrays_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Ejemplo array
ejemplo_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Este es un array: " , ejemplo_array)

Este es un array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# acceder a una posición por su indice
print(ejemplo_array[2]) # los indices comienzan desde la posición 0
print(ejemplo_array[7])


# Ejemplo con varios indices y el último indice
print(ejemplo_array[[7,10,-1]])  # el último elemento se trae con el -1

3
8
[ 8 11 20]


In [ ]:
# accedor a un rango del array
print(ejemplo_array[1:4]) # los dos puntos significa rango

[2 3 4]


In [ ]:
# acceder a los primeros 3 números
print(ejemplo_array[:3])

[1 2 3]


In [ ]:
# acceder a los últimos 3 numeros
print(ejemplo_array[-3:])

[18 19 20]


In [ ]:
#EJERCICIOS PRACTICOS CON ARRAYS
temperaturas = np.array([15,18,22,25,24,20,17])

In [ ]:
#Reto 1 (Indexación simple): Extraer el primer elemento 15 y el último elemento 17
print(temperaturas[0:-1])

[15 18 22 25 24 20]


In [ ]:
array[-1] → el último elemento.
array[-2] → el penúltimo.
array[-3:] → desde la antepenúltima posición hasta el final (los últimos 3 elementos).
array[:-2] → todo excepto los últimos 2 elementos.

In [1]:
temperaturas = [18, 21, 19, 25, 30, 22, 17]
print(temperaturas[-1])    # 17  (el último)
print(temperaturas[-3:])   # [30, 22, 17]  (últimos 3)
print(temperaturas[:-2])   # [18, 21, 19, 25, 30]  (todos menos los últimos 2)

17
[30, 22, 17]
[18, 21, 19, 25, 30]


In [4]:
# OTRO EJEMPLO
temperaturas = [18, 21, 19, 25, 30, 22, 17]
print(temperaturas[-4:-1])  #[25,30,22]
print(temperaturas[::3])

[25, 30, 22]
[18, 25, 17]
