<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/clase2_librerias_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Vamos a trabjar con NUMPY
import numpy as np

In [2]:
lista = [1,2,3,4,5,6]
array = np.array([1,2,3,4,5]) # esto convierte la lista en array

In [3]:
print("Lista:", lista)
print("Array:", array)

Lista: [1, 2, 3, 4, 5, 6]
Array: [1 2 3 4 5]


In [4]:
print(type(lista)) ## muestra el tipo de dato
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
# sumar los elementos con función SUM para un array

print("La suma de los elementos es: " , array.sum())

La suma de los elementos es:  15


In [9]:
suma_lista = 0
for num in lista:
    suma_lista += num # Esto es para crear la suma de una lista
print("La suma de los elementos de la lista es: ", suma_lista)

La suma de los elementos de la lista es:  21


In [10]:
# Función muliplicación
doble_array = array * 2
print("El doble de los elementos del array es: ", doble_array)

El doble de los elementos del array es:  [ 2  4  6  8 10]


In [12]:
# PROPIEDADES DEL ARRAY
print("Dimensión del array: ", array.ndim)
print("Forma del array: ", array.shape)
print("Tamaño del array: ", array.size)
print("Tipo de dato del array: ", array.dtype)

Dimensión del array:  1
Forma del array:  (5,)
Tamaño del array:  5
Tipo de dato del array:  int64


In [14]:
# EJERCICIO ARRAY 2
#Ejercicio 2.1
#Explora el array
numeros = np.array([10,20,30,40,50])
print("El array es: ", numeros)
print("Dimensión del array: ", numeros.ndim)
print("Forma del array: ", numeros.shape)
print("Tamaño del array: ", numeros.size)
print("Tipo de dato del array: ", numeros.dtype)

El array es:  [10 20 30 40 50]
Dimensión del array:  1
Forma del array:  (5,)
Tamaño del array:  5
Tipo de dato del array:  int64


In [16]:
# Ejercicio 2.2
#Realiza operaciones: crea nuevos arrays con:
numeros + 5


array([15, 25, 35, 45, 55])

In [17]:
numeros * 5

array([ 50, 100, 150, 200, 250])

In [18]:
numeros ** 2

array([ 100,  400,  900, 1600, 2500])

In [19]:
# Ejercicio 2.3
# Calcular la suma y el promedio
print("La suma de los elementos del array es: ", numeros.sum())
print("El promedio de los elementos del array es: ", numeros.mean())

La suma de los elementos del array es:  150
El promedio de los elementos del array es:  30.0


In [21]:
# Ejercicio 3
# Crear un array precios con
precios = np.array([10000,15000,20000,25000,30000])

In [22]:
# 3.1 Calcular el precio con el 10% de aumento
precios_aumento = precios * 1.1
print("El precio con el 10% de aumento es: ", precios_aumento)

El precio con el 10% de aumento es:  [11000. 16500. 22000. 27500. 33000.]


In [23]:
# otra opción para clacular el 10% de aumento
precios_aumento = precios + (precios * 0.1)
print("El precio con el 10% de aumento es: ", precios_aumento)

El precio con el 10% de aumento es:  [11000. 16500. 22000. 27500. 33000.]
